# These are supported funding model platforms

github: maxwarzet
telegram: MakhmudHojiev
instagram: domenmaxwar
email: hojievmakhmud@gmail.com
portfolio: https://makhfolio.vercel.app/
Name: Makhmud
Surname: Hojiev
linkedin: https://www.linkedin.com/in/makhmud-hojiev
